name: IBas Docker Image
on:
  push:
    branches: [ main ]
env:
  IMAGENAME: ${{ secrets.REGISTRY_LOGIN_SERVER}}/ibasemployeeservice:latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t $IMAGENAME
        docker push $IMAGENAME
